name: ZER08 Job Scheduler

on:
  schedule:
    # Run every minute
    - cron: '* * * * *'
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  trigger-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger job processing endpoint
        run: |
          curl -X GET "${{ secrets.API_URL }}/api/jobs/trigger" \
            -H "x-auth-token: ${{ secrets.GITHUB_ACTION_SECRET }}" \
            -H "Content-Type: application/json" \
            --fail
        env:
          API_URL: ${{ secrets.API_URL }}

      - name: Log outcome
        if: ${{ always() }}
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Job scheduler executed successfully."
          else
            echo "Job scheduler failed. Please check the logs."
          fi